version: "3.8"

services:
    php:
        build: phpfpm
        restart: always
        container_name: phpfpm_local
        volumes:
            - ./www:/var/www/html
        networks:
            - dev1
        environment:
            TZ: Asia/Seoul
    nginx:
        build: nginx
        restart: always
        container_name: nginx_local
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html                # web root directory mount
            - ./nginx_conf:/etc/nginx/conf.d          # web server setting directory mount
        networks:
            - dev1
        environment:
            TZ: Asia/Seoul
    db:
        image: mysql:8.0.33
        restart: always
        container_name: mysql8
        ports:
            -   3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_USER: admin
            MYSQL_PASSWORD: 1234
            TZ: Asia/Seoul
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - dev1

networks:
    dev1:
